"use client";
import { useState } from "react";
type Mode="login"|"register"|"forgot";
export default function AdminLogin({hasAdmin}:{hasAdmin:boolean}){
 const [mode,setMode]=useState<Mode>(hasAdmin?"login":"register"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[recovery,setRecovery]=useState(""),[notice,setNotice]=useState("");
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[pin,setPin]=useState(""),[code,setCode]=useState(""),[setupCode,setSetupCode]=useState(""),[newPassword,setNewPassword]=useState("");
 function switchMode(next:Mode){setMode(next);setError("");setNotice("");setRecovery("");setPassword("");setPin("")}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const body=mode==="register"?{action:"register",email,password,pin,setupCode}:mode==="login"?{action:"login",email,password,pin}:{action:"reset",email,pin,recoveryCode:code,newPassword};const r=await fetch('/api/admin/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d:{error?:string;recoveryCode?:string}=await r.json();if(!r.ok)throw Error(d.error||'تعذرت العملية');setPassword("");setPin("");if(mode==="login"){window.location.href='/admin';return}if(d.recoveryCode){setRecovery(d.recoveryCode);setNotice(mode==="register"?'تم إنشاء حساب الإدارة. احفظ رمز الاسترداد قبل المتابعة.':'تم تغيير كلمة المرور. احفظ رمز الاسترداد الجديد.')}}catch(e){setError(e instanceof Error?e.message:'تعذرت العملية')}finally{setBusy(false)}}
 return <main className="admin-shell"><div className="admin-wrap"><div className="admin-top"><a className="admin-brand" href="/">تصاميمك</a><a href="/">العودة للموقع</a></div><h1 className="admin-title">صفحة إدارة تصاميمك</h1><p className="admin-lead">حساب الإدارة مستقل عن حسابات مستخدمي الموقع. استخدمه لتعديل أسعار التصاميم والاشتراكات.</p><section className="admin-card admin-login-card"><div className="admin-tabs" role="tablist" aria-label="حساب الإدارة"><button type="button" className={mode==='login'?'active':''} onClick={()=>switchMode('login')}>تسجيل دخول</button><button type="button" className={mode==='register'?'active':''} onClick={()=>switchMode('register')}>إنشاء حساب</button><button type="button" className={mode==='forgot'?'active':''} onClick={()=>switchMode('forgot')}>نسيت كلمة المرور؟</button></div>
 {recovery?<div className="admin-recovery" role="status"><h2>رمز الاسترداد</h2><p>{notice} لن يظهر هذا الرمز مرة أخرى. يلزم مع الرمز الشخصي لاستعادة كلمة المرور.</p><code>{recovery}</code><button type="button" className="admin-primary" onClick={()=>mode==='register'?window.location.assign('/admin'):switchMode('login')}>{mode==='register'?'حفظت الرمز، دخول الإدارة':'حفظت الرمز، تسجيل الدخول'}</button></div>:
 mode==='register'&&hasAdmin?<p>تم إنشاء حساب الإدارة سابقًا. سجّل الدخول أو استخدم استعادة كلمة المرور.</p>:
 <form onSubmit={submit}><label className="admin-field">البريد الإلكتروني<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="name@example.com" /></label>{mode==='login'||mode==='register'?<label className="admin-field">كلمة المرور<input type="password" autoComplete={mode==='login'?"current-password":"new-password"} minLength={mode==='register'?12:undefined} value={password} onChange={e=>setPassword(e.target.value)} required /></label>:null}<label className="admin-field">الرمز الشخصي · 4 أرقام<input type="password" inputMode="numeric" autoComplete="off" pattern="[0-9]{4}" minLength={4} maxLength={4} value={pin} onChange={e=>setPin(e.target.value)} required /></label>{mode==='forgot'?<><p>تحتاج رمز الاسترداد الذي حفظته عند إنشاء حساب الإدارة، بالإضافة إلى رمزك الشخصي.</p><label className="admin-field">رمز الاسترداد<input type="text" autoComplete="off" value={code} onChange={e=>setCode(e.target.value)} minLength={32} maxLength={32} required /></label><label className="admin-field">كلمة المرور الجديدة<input type="password" autoComplete="new-password" minLength={12} value={newPassword} onChange={e=>setNewPassword(e.target.value)} required /></label></>:null}{mode==='register'?<label className="admin-field">رمز إعداد الإدارة<input type="password" autoComplete="off" value={setupCode} onChange={e=>setSetupCode(e.target.value)} required placeholder="رمز إعداد أول حساب إدارة" /></label>:null}<button className="admin-primary" type="submit" disabled={busy}>{busy?'جارٍ المعالجة...':mode==='login'?'دخول وتحميل البيانات':mode==='register'?'إنشاء حساب الإدارة':'إعادة تعيين كلمة المرور'}</button></form>}
 {error&&<p role="alert" className="admin-error">{error}</p>}</section></div></main>
}
