"use client";
import { useEffect, useState } from "react";
const initial = {single:"1.00",month:"5.00",two:"7.00"};
export default function AdminPanel({email}:{email:string}) {
  const [v,setV]=useState(initial),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
  useEffect(()=>{fetch('/api/prices',{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error();return await r.json() as {prices:Record<keyof typeof initial,number>}}).then(d=>{setV({single:(d.prices.single/1000).toFixed(2),month:(d.prices.month/1000).toFixed(2),two:(d.prices.two/1000).toFixed(2)});setLoaded(true)}).catch(()=>setStatus('تعذر تحميل الأسعار. حاول تحديث الصفحة.'))},[]);
  async function save(e:React.FormEvent){e.preventDefault();let prices:Record<string,number>={};for(const k of Object.keys(v) as (keyof typeof v)[]){const n=Number(v[k]);if(!Number.isFinite(n)||n<.5||n>1000||Math.round(n*1000)!==n*1000){setStatus('أدخل أسعارًا صحيحة، حتى 3 منازل عشرية.');return}prices[k]=Math.round(n*1000)}setBusy(true);setStatus('جارٍ الحفظ...');try{const r=await fetch('/api/prices',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({prices})});const d:{error?:string}=await r.json();if(!r.ok)throw Error(d.error||'تعذر الحفظ');setStatus('تم حفظ الأسعار. ستظهر عند تحديث صفحة الموقع.')}catch(e){setStatus(e instanceof Error?e.message:'تعذر الحفظ')}finally{setBusy(false)}}
  async function logout(){await fetch('/api/admin/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});window.location.href='/admin'}
  const field=(key:keyof typeof v,label:string)=><label className="admin-field">{label}<input type="number" min="0.5" max="1000" step="0.001" inputMode="decimal" value={v[key]} onChange={e=>setV({...v,[key]:e.target.value})} required aria-label={`${label} بالدينار الأردني`} /></label>;
  return <main className="admin-shell"><div className="admin-wrap"><header className="admin-top"><a className="admin-brand" href="/">تصاميمك</a><div className="admin-top-actions"><a href="/">عرض الموقع</a><button type="button" onClick={logout}>تسجيل الخروج</button></div></header><h1 className="admin-title">صفحة إدارة تصاميمك</h1><p className="admin-account">حساب المالك: {email}</p><div className="admin-grid"><section className="admin-card"><h2>أسعار الباقات</h2><p>عدّل الأسعار بالدينار الأردني، ثم اضغط حفظ لتظهر في الموقع.</p><form className="admin-panel-form" onSubmit={save}>{field('single','تصميم واحد')}{field('month','اشتراك شهر')}{field('two','اشتراك شهرين')}<button className="admin-primary" type="submit" disabled={!loaded||busy}>{busy?'جارٍ الحفظ...':'حفظ الأسعار'}</button><div role="status" className="admin-status">{status}</div></form></section><section className="admin-card"><h2>استلام الأرباح</h2><div className="admin-state">بوابة الدفع غير مربوطة</div><p>بعد فتح حساب تاجر، أضف الحساب البنكي أو عدّله في لوحة مزوّد الدفع. تغيير الرقم داخل الموقع وحده لا يغيّر وجهة التحويل، لذلك لا نجمع بياناتك البنكية هنا قبل الربط.</p><p>ستظهر حالة الحساب هنا بعد تفعيل بوابة الدفع.</p></section></div></div></main>;
}
